stages:
  - fmt
  - lint

variables:
  GOMODCACHE: "$CI_PROJECT_DIR/.cache/pkg/mod"
  GOPATH: "$CI_PROJECT_DIR/.cache/gopath"
  GOFLAGS: "-mod=readonly"

default: &default
  image: golang:1.25.1
  before_script:
    - mkdir -p "$GOMODCACHE" "$GOPATH"
    - export PATH="$GOPATH/bin:$PATH"
    - go env
    - go version

cache:
  key:
    files:
      - go.sum
  paths:
    - .cache/pkg/mod
    - .cache/gopath

format-check:
  <<: *default
  stage: fmt
  script:
    # install gofumpt if not already cached
    - if [ ! -x "$GOPATH/bin/gofumpt" ]; then go install mvdan.cc/gofumpt@v0.4.0; fi
    - CHANGED=$(gofumpt -l . | wc -l)
    - if [ "$CHANGED" -ne 0 ]; then echo "Files not gofumpt-formatted:"; gofumpt -l .; exit 1; fi
  cache:
    policy: pull-push
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH

lint:
  <<: *default
  stage: lint
  script:
    # install golangci-lint if not cached
    - if [ ! -x "$GOPATH/bin/golangci-lint" ]; then curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$GOPATH/bin" v1.59.0; fi
    - export PATH="$GOPATH/bin:$PATH"
    - golangci-lint version
    - golangci-lint run ./...
  cache:
    policy: pull-push
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH

test:
  <<: *default
  stage: test
  script:
    - golangci-lint test
  cache:
    policy: pull-push
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH
